GET http://localhost:5000/


###

DELETE  http://localhost:3000/users/delete
Content-Type: application/json

{
    "email":"shmuel13e@gmail.com"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email":"shmuel13e@gmail.com",
    "password":"11"
}


###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name":"shmuel",
    "email":"shmuellk@gmail.com",
    "phone":"0534217016",
    "password":"11",
    "userName":"shmuell"
}

###

POST http://localhost:3000/auth/resend
Content-Type: application/json

{
    "email":"shmuellk32@gmail.com"
}

###

POST http://localhost:3000/auth/verify
Content-Type: application/json

{
    "email":"shmuellk32@gmail.com",
    "code":"674769"
}


###

GET http://localhost:5000/users/getUsersComplit
Content-Type: application/json

{
    "data": "l1"
}